# Generated by Django 4.1.7 on 2023-03-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210403_2153"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="current_bill",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="profile", name="water_bill", field=models.FloatField(null=True),
        ),
    ]
